#!/usr/bin/env php
<?php
/*--------------------------------------------------------------------------------|
|													ALTVEL FRAMEWORK CONSTANTS															|
|								Please do not tamper with the following constants 								|
---------------------------------------------------------------------------------*/

define('DS', DIRECTORY_SEPARATOR);
define('ROOT', __DIR__);

/*
|
|---------------------------------------------------------------------------------|
|												ALTVEL AUTOLOAD																						|
|---------------------------------------------------------------------------------|
|
*/

require __DIR__.'/vendor/autoload.php';

$file = "";
if (file_exists(".env")) {
	$file = ".env";
}else{
	$file = ".env.example";
}

if (!file_exists($file)) {
	throw new Exception(
		"No .env OR .env.example files. please craete one with the following
		dependencies: \n 'DB_HOST', 'DB_NAME', 'DB_USER', 'DB_PASS', 'DB_DRIVER'
		", 1);
}

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__.'/.env.example');
$dotenv->load();

$dotenv->required(['DB_HOST', 'DB_NAME', 'DB_USER', 'DB_PASS', 'DB_DRIVER']);

array_shift($argv);
$argc = count($argv);

if ($argc === 0) {
	exit(
		"Welcome To The Altvel Framework Engineer Console:\n\n".
		"Oops!! To see available commands, Enter: php Engineer app::help"
	);
}

Seven\Consoler\Console::Parse($argc, $argv);

exit();